name: Backend CI - Personal Finance Tracker

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest


    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Backend Health Check
      run: |
        uvicorn app.main:app --host 127.0.0.1 --port 8000 &
        sleep 5
        curl --fail http://127.0.0.1:8000/ || exit 1

    - name: Run Backend Tests
      env:
        PYTHONPATH: .
      run: |
        pytest --cov=app --cov-report=term-missing
      
